In [2]:
import torch 
import numpy as np

In [3]:
# Device configuration
print(f"Is MPS (Metal Performance Shader) built? {torch.backends.mps.is_built()}")
print(f"Is MPS available? {torch.backends.mps.is_available()}")

device = "mps" if torch.backends.mps.is_available() else "cpu"
device = torch.device(device)
print(f"Using device: {device}")

Is MPS (Metal Performance Shader) built? True
Is MPS available? True
Using device: mps


**Tensors initialization** 

In [4]:
numpy_array=np.array([[1,2],[3,4]])
tensor=torch.from_numpy(numpy_array)
original_numpy_array=tensor.numpy()

print(numpy_array)
print(tensor)
print(original_numpy_array)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]


**Tensors' operations**

In [7]:
x1=torch.rand(2,2)
x2=torch.rand(2,2)

print(x1)
print(x2)

#not in place operation
y=x1+x2
print(y)

#in place operation
x2.add_(x1)
print(x2)

x3=torch.arange(6)
print(x3)
print("shape x3:{}".format(x3.shape))
x3=x3.view(2,3)
print(x3)
print("new shape x3:{}".format(x3.shape))

matrix_multiplication=torch.mm(x1,x2)
print(matrix_multiplication)

#first row x3
element_1_1=x3[0,0]
first_row=x3[0,:]
first_column=x3[:,0]
first_2_elements_first_row=x3[0,:2]
print(element_1_1)
print(first_row)
print(first_column)
print(first_2_elements_first_row)

tensor([[0.4549, 0.9559],
        [0.1676, 0.9642]])
tensor([[0.3067, 0.5819],
        [0.1108, 0.9424]])
tensor([[0.7615, 1.5377],
        [0.2784, 1.9066]])
tensor([[0.7615, 1.5377],
        [0.2784, 1.9066]])
tensor([0, 1, 2, 3, 4, 5])
shape x3:torch.Size([6])
tensor([[0, 1, 2],
        [3, 4, 5]])
new shape x3:torch.Size([2, 3])
tensor([[0.6125, 2.5219],
        [0.3961, 2.0961]])
tensor(0)
tensor([0, 1, 2])
tensor([0, 3])
tensor([0, 1])


**Define the Dataset**

In [8]:
from torch.utils.data import Dataset, DataLoader
from torch.nn import functional
data_array=np.random.randn(100,10)
labels_array=np.random.randint(0,2,(100,))

data=torch.from_numpy(data_array).to(torch.float32)
labels=torch.from_numpy(labels_array)
labels=functional.one_hot(labels).to(torch.float32)

class customDataset(Dataset):
    def __init__(self,data,labels):
        self.data=data
        self.labels=labels
    def __getitem__(self,idx):
        return self.data[idx],self.labels[idx]
    def __len__(self):
        return self.data.shape[0]


idx=0
custom_dataset=customDataset(data,labels)
print("total length dataset:{}".format(custom_dataset.__len__()))
print("{}th element in the dataset is:{}".format(idx,custom_dataset.__getitem__(idx)[0]))
print("with corresponding label:{}".format(custom_dataset.__getitem__(idx)[1]))



total length dataset:100
0th element in the dataset is:tensor([-0.4458, -1.4070, -1.2872, -0.4806,  0.8663, -1.5466, -1.0227, -0.4903,
         0.1568, -0.2836])
with corresponding label:tensor([1., 0.])


**Define the Dataloader**

In [9]:
Data_loader=DataLoader(custom_dataset,batch_size=5,shuffle=False)
for x,y in Data_loader:
    print(x.shape)
    print(y.shape)

torch.Size([5, 10])
torch.Size([5, 2])
torch.Size([5, 10])
torch.Size([5, 2])
torch.Size([5, 10])
torch.Size([5, 2])
torch.Size([5, 10])
torch.Size([5, 2])
torch.Size([5, 10])
torch.Size([5, 2])
torch.Size([5, 10])
torch.Size([5, 2])
torch.Size([5, 10])
torch.Size([5, 2])
torch.Size([5, 10])
torch.Size([5, 2])
torch.Size([5, 10])
torch.Size([5, 2])
torch.Size([5, 10])
torch.Size([5, 2])
torch.Size([5, 10])
torch.Size([5, 2])
torch.Size([5, 10])
torch.Size([5, 2])
torch.Size([5, 10])
torch.Size([5, 2])
torch.Size([5, 10])
torch.Size([5, 2])
torch.Size([5, 10])
torch.Size([5, 2])
torch.Size([5, 10])
torch.Size([5, 2])
torch.Size([5, 10])
torch.Size([5, 2])
torch.Size([5, 10])
torch.Size([5, 2])
torch.Size([5, 10])
torch.Size([5, 2])
torch.Size([5, 10])
torch.Size([5, 2])


**Define a simple multy-layer perceptron**

In [10]:
from torch import nn

class MLP(nn.Module):
    def __init__(self,hidden_layers_dimension,input_dimensions,output_dimensions):
        
        super(MLP, self).__init__()
        self.fc1=nn.Linear(input_dimensions,hidden_layers_dimension)
        self.act=nn.ReLU()
        self.output_layer=nn.Linear(hidden_layers_dimension,output_dimensions)
        
    def forward(self,x):
        
        x=self.fc1(x)
        x=self.act(x)
        x=self.output_layer(x)
    
        return x

mlp=MLP(12,10,2)
result=mlp(data)
print(result.shape)

torch.Size([100, 2])


**Define the loss function**

In [11]:
criterion=torch.nn.CrossEntropyLoss()

**Define the optimizer**

In [12]:
from torch.optim import Adam
lr=0.05
optimizer=Adam(mlp.parameters(),lr)

**Training loop**

In [13]:
import tqdm
n_epochs=20
mlp.train()
mlp.to(device)

# Training loop
for epoch in range(n_epochs):
    print("epoch:{}".format(epoch))
    loss_current_epoch=[]
    for data_inputs, data_labels in Data_loader:

        data_inputs = data_inputs.to(device)
        data_labels = data_labels.to(device)

        preds = mlp(data_inputs)
        preds = preds.squeeze(dim=1)

        loss = criterion(preds, data_labels)
        
        loss_current_epoch.append(loss.item())
        optimizer.zero_grad()
        loss.backward()

        optimizer.step()
    
    print("loss epoch:{} is:{}".format(epoch,np.mean(loss_current_epoch)))

epoch:0
loss epoch:0 is:0.8692811667919159
epoch:1
loss epoch:1 is:0.726115682721138
epoch:2
loss epoch:2 is:0.6358610585331916
epoch:3
loss epoch:3 is:0.6216837272047997
epoch:4
loss epoch:4 is:0.5695558935403824
epoch:5
loss epoch:5 is:0.5486934676766395
epoch:6
loss epoch:6 is:0.5297417521476746
epoch:7
loss epoch:7 is:0.5004117213189602
epoch:8
loss epoch:8 is:0.46870013549923895
epoch:9
loss epoch:9 is:0.4743284583091736
epoch:10
loss epoch:10 is:0.4540164075791836
epoch:11
loss epoch:11 is:0.48188488446176053
epoch:12
loss epoch:12 is:0.4858164742588997
epoch:13
loss epoch:13 is:0.4365636073052883
epoch:14
loss epoch:14 is:0.37304792925715446
epoch:15
loss epoch:15 is:0.38000732138752935
epoch:16
loss epoch:16 is:0.4117301650345325
epoch:17
loss epoch:17 is:0.36357328183948995
epoch:18
loss epoch:18 is:0.3500608140602708
epoch:19
loss epoch:19 is:0.3949670232832432


**Evaluate the model**

In [14]:
data_array_test=np.random.randn(100,10)
labels_array_test=np.random.randint(0,2,(100,))

data_test=torch.from_numpy(data_array_test).to(torch.float32)
labels_test=torch.from_numpy(labels_array_test).to(torch.float32)

mlp.eval() 
mlp.to(device)
true_preds, num_preds = 0., 0.

custom_dataset_test=customDataset(data_test,labels_test)
Data_loader_test=DataLoader(custom_dataset_test,batch_size=5,shuffle=False)



with torch.no_grad(): 
    for data_inputs, data_labels in Data_loader_test:


        data_inputs, data_labels = data_inputs.to(device), data_labels.to(device)
        preds = mlp(data_inputs)
        preds = preds.squeeze(dim=1)

        pred_labels = torch.argmax(preds,1) 

        true_preds += (pred_labels == data_labels).sum()
        num_preds += data_labels.shape[0]

acc = true_preds / num_preds
print(f"Accuracy of the model: {100.0*acc:4.2f}%")

Accuracy of the model: 44.00%
